spring:
  datasource:
    url: jdbc:mysql://localhost:3306/download?useSSL=false
    username: root
    password: Chen781+-/
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  # 下载配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 20MB
  mail:
    host: smtp.qq.com
    username: 1219853295@qq.com
    password: fgjbhgusxwomiifd
    properties:
      mail:
        smtp:
          ssl:
            enable: true
# 文件路径
file.upload.dir: c:/test

# mybatis
mybatis:
  type-aliases-package: com.chen.dao
  configuration:
    map-underscore-to-camel-case: true