spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: Chen781+-/
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  # ???????????????
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 20MB
# ?????
file.upload.dir: d:/test